queue_rules:
  - name: default
    conditions: []  # no extra conditions needed to get merged

pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success=Lint Code Base
      - status-success=Build
      - status-success=Deploy
    actions:
      queue:
        name: default
        method: rebase
  - name: automatic merge for Scala Steward pull requests
    conditions:
      - author=dhpiggott
      - head~=^update\/
      - status-success=Lint Code Base
      - status-success=Build
      - status-success=Deploy
    actions:
      queue:
        name: default
        method: rebase
